In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv('data.csv', header=None)
X = np.array(data.iloc[:, [0, 1]])
y = np.array(data.iloc[:, 2])

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1000)

In [4]:
def rs(result, y):
    print(result)
    print(y)
    print(accuracy_score(result, y))

# SVM

In [5]:
from sklearn.svm import SVC

## GridSearch

In [6]:
model  = SVC(gamma='auto')
parameters = {
    'C' : [1, 2, 3, 4, 5],
    'kernel' : ['linear', 'poly', 'rbf', 'sigmoid'],
    'decision_function_shape' : ['ovo', 'ovr'],
}

In [7]:
gr = GridSearchCV(model, parameters, cv=4)
gr.fit(X_train, y_train)
gr.best_params_

{'C': 1, 'decision_function_shape': 'ovo', 'kernel': 'linear'}

## Predict

In [8]:
model = SVC(C=1, decision_function_shape='ovo', kernel='linear')
model.fit(X_train, y_train)
svm_result = model.predict(X_test)
rs(svm_result, y_test)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0]
0.85


# Decision Tree

In [9]:
from sklearn.tree import DecisionTreeClassifier

## GridSearch

In [10]:
model = DecisionTreeClassifier()
parameters = {
    'splitter' : ['random', 'best'],
    'presort' : [True, False]
}
gr = GridSearchCV(model, parameters, cv=4, iid=True)
gr.fit(X_train, y_train)
gr.best_params_

{'presort': True, 'splitter': 'best'}

## Predict

In [11]:
model = DecisionTreeClassifier(presort=True, splitter='best')
model.fit(X_train, y_train)
tree_result = model.predict(X_test)
rs(tree_result, y_test)

[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0]
[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0]
1.0


# MLPClassifier

In [12]:
from sklearn.neural_network import MLPClassifier

## GridSearch

model = MLPClassifier(hidden_layer_sizes=76)
parameters = {
    'activation' : ['identity', 'logistic', 'tanh', 'relu'],
    'solver' : ['lbfgs', 'sgd', 'adam'],
    'learning_rate' : ['constant', 'invscaling', 'adaptive'],
    'shuffle' : [True, False],
    'momentum' : [0.5, 0.6, 0.7, 0.8, 0.9, 1]
}
gr = GridSearchCV(model, parameters, cv=4)
gr.fit(X_train, y_train)
gr.best_params_

Google Colab:
{'activation': 'tanh',
 'learning_rate': 'adaptive',
 'momentum': 1,
 'shuffle': True,
 'solver': 'lbfgs'}

## Predict

In [13]:
model = MLPClassifier(hidden_layer_sizes=76, activation='tanh', learning_rate='adaptive', momentum=1, shuffle=True, solver='lbfgs')
model.fit(X_train, y_train)
pla_result = model.predict(X_test)
rs(pla_result, y_test)

[1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0]
[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0]
0.9
