In [1]:
import numpy as np

# EX 1

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
for i, j in enumerate(a):
    if j>3 and j<8:
        a[i] *= -1
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

# EX 2

In [3]:
vector = np.random.randint(0, 100, size=10)
print(vector)
ln = vector.max()
vector[vector == ln] = 0
print(vector)

[72 77 64 72 75 73 24 98 73 13]
[72 77 64 72 75 73 24  0 73 13]


# EX 3

In [4]:
a = np.random.randint(0, 10, (3, 2))
b = np.random.randint(0, 10, (3, 2))
tmp = {i for j in a for i in j}
tmp.update({i for j in b for i in j})
tmp

{0, 1, 2, 3, 6, 8, 9}

# EX 4

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a = a[::-1]
a

array([6, 5, 4, 3, 2, 1])

# EX 5

In [6]:
a = np.random.randint(0, 9, (3, 3))
a

array([[1, 5, 1],
       [7, 4, 7],
       [5, 7, 0]])

# EX 6

In [7]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0)

(array([0, 1, 4], dtype=int64),)

# EX 7

In [8]:
a = np.random.randint(9, size=(3, 3, 3))
a

array([[[2, 6, 6],
        [8, 3, 2],
        [7, 4, 2]],

       [[1, 7, 3],
        [4, 8, 5],
        [2, 6, 3]],

       [[6, 2, 7],
        [0, 8, 2],
        [8, 5, 2]]])

# EX 8

In [9]:
a = np.random.randint(100, size=30)
a.mean()

52.733333333333334

# EX 9

In [10]:
a = np.ones([5, 5])
a[1:4, 1:4] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# EX 10

In [11]:
x = np.random.randint(0, 100, 20)
y = np.random.uniform(0, 20)
ab = np.abs(x - y)
nn = ab.min()
np.where(ab == nn)

(array([11], dtype=int64),)