In [1]:
import numpy as np

# EX 1

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
for i, j in enumerate(a):
    if j>3 and j<8:
        a[i] *= -1
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

# EX 2

In [3]:
vector = np.random.randint(0, 100, size=10)
print(vector)
ln = vector.max()
vector[vector == ln] = 0
print(vector)

[43 46 10 19 25 44  5 34 86 33]
[43 46 10 19 25 44  5 34  0 33]


# EX 3

In [4]:
a = np.random.randint(0, 10, (3, 2))
b = np.random.randint(0, 10, (3, 2))
rs = np.intersect1d(a, b)
rs

array([2])

# EX 4

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a = a[::-1]
a

array([6, 5, 4, 3, 2, 1])

# EX 5

In [6]:
a = np.random.randint(0, 9, (3, 3))
a

array([[5, 2, 3],
       [1, 0, 3],
       [2, 0, 8]])

# EX 6

In [7]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0)

(array([0, 1, 4], dtype=int64),)

# EX 7

In [8]:
a = np.random.randint(9, size=(3, 3, 3))
a

array([[[4, 7, 4],
        [4, 1, 0],
        [8, 0, 1]],

       [[6, 4, 2],
        [6, 6, 0],
        [0, 4, 2]],

       [[3, 4, 6],
        [1, 8, 4],
        [4, 5, 3]]])

# EX 8

In [9]:
a = np.random.randint(100, size=30)
a.mean()

45.233333333333334

# EX 9

In [10]:
a = np.ones([5, 5])
a[1:4, 1:4] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# EX 10

In [11]:
x = np.random.randint(0, 100, 20)
y = np.random.uniform(0, 20)
ab = np.abs(x - y)
nn = ab.min()
np.where(ab == nn)

(array([5], dtype=int64),)